components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
  schemas:
    LogAssessmentRequest:
      type: object
      properties:
        UserId:
          type: string
          description: Unique user ID of the GPT user
        AssessmentResult:
          type: object
          properties:
            Questions:
              type: array
              items:
                type: string
              description: List of assessment questions
            Answers:
              type: array
              items:
                type: integer
              description: List of answers corresponding to the questions
            Attribute:
              type: array
              items:
                type: string
              description: List of attribute names
            AttributeValues:
              type: array
              items:
                type: string
              description: List of attribute values
            Score:
              type: integer
              description: Numeric score of the assessment
            Feedback:
              type: string
              description: Qualitative feedback
            CompletedAt:
              type: string
              format: date-time
              description: ISO 8601 timestamp of completion
          required:
            - Score
            - Feedback
            - CompletedAt
      required:
        - UserId
        - AssessmentResult
